require('dotenv').config()
const express = require('express')
const cors = require('cors')
const app = express()
app.use(express.json())
app.use(cors({credentials: true, origin: process.env.ORIGIN}))
app.use(express.static('public'))
const EmailRoutes = require('./routes/EmailRoutes')
app.use('/email', EmailRoutes)
app.listen(process.env.PORT)